# Generated by Django 3.1.5 on 2021-01-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='brewer',
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('O', 'orange'), ('B', 'brown'), ('Y', 'yellow')], default='APA', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.CharField(choices=[('APA', 'American Pale Ale'), ('IPA', 'Indian Pale Ale'), ('S', 'Stout'), ('WB', 'Wheat Beer'), ('PO', 'Porter'), ('BPA', 'Belgian Pale Ale'), ('B', 'Bock'), ('EPA', 'English Pale Ale'), ('P', 'Pilsner'), ('D', 'Dubbel'), ('T', 'Triple'), ('Q', 'Quadruple')], default='O', max_length=20),
            preserve_default=False,
        ),
    ]
