# Generated by Django 3.1.5 on 2021-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210131_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brewer',
            field=models.CharField(max_length=100),
        ),
    ]
