# Generated by Django 3.1.5 on 2021-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210201_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='percentage',
            field=models.FloatField(max_length=2),
        ),
    ]
