# Generated by Django 3.1.5 on 2021-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210201_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Y', 'Yellow'), ('DK', 'Dark Yellow'), ('LO', 'Light Orange'), ('A', 'Amber'), ('LB', 'Ligth Brown'), ('B', 'Brown'), ('DB', 'Dark Brown'), ('BK', 'Black')], default='Y', max_length=2),
            preserve_default=False,
        ),
    ]
