# Generated by Django 3.1.5 on 2021-02-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Y', 'Yellow'), ('DK', 'Dark Yellow'), ('LO', 'Light Orange'), ('A', 'Amber'), ('LB', 'Light Brown'), ('B', 'Brown'), ('DB', 'Dark Brown'), ('BK', 'Black')], max_length=2),
        ),
    ]
